export const CARRINHO_ADD_ITEM = 'CARRINHO_ADD_ITEM';
export const CARRINHO_REMOVER_ITEM = 'CARRINHO_REMOVER_ITEM';
export const CARRINHO_SALVAR_ENDERECO = 'CARRINHO_SALVAR_ENDERECO';
export const CARRINHO_SALVAR_PAGAMENTO = 'CARRINHO_SALVAR_PAGAMENTO';
export const CARRINHO_VAZIO = 'CARRINHO_VAZIO';