export const PEDIDO_CRIAR_REQUEST = 'PEDIDO_CRIAR_REQUEST';
export const PEDIDO_CRIAR_SUCESSO = 'PEDIDO_CRIAR_SUCESSO';
export const PEDIDO_CRIAR_FALHA = 'PEDIDO_CRIAR_FALHA';
export const PEDIDO_CRIAR_RESET = 'PEDIDO_CRIAR_RESET';

export const PEDIDO_DETALHES_REQUEST = 'PEDIDO_DETALHES_REQUEST';
export const PEDIDO_DETALHES_SUCESSO = 'PEDIDO_DETALHES_SUCESSO';
export const PEDIDO_DETALHES_FALHA = 'PEDIDO_DETALHES_FALHA';

export const PEDIDOS_HISTORICO_REQUEST = 'PEDIDOS_HISTORICO_REQUEST';
export const PEDIDOS_HISTORICO_SUCESSO = 'PEDIDOS_HISTORICO_SUCESSO';
export const PEDIDOS_HISTORICO_FALHA = 'PEDIDOS_HISTORICO_FALHA';

export const PEDIDOS_ADM_REQUEST = 'PEDIDOS_ADM_REQUEST';
export const PEDIDOS_ADM_SUCESSO = 'PEDIDOS_ADM_SUCESSO';
export const PEDIDOS_ADM_FALHA = 'PEDIDOS_ADM_FALHA';

export const PEDIDOS_ADM_DELETAR_REQUEST = 'PEDIDOS_ADM_DELETAR_REQUEST';
export const PEDIDOS_ADM_DELETAR_SUCESSO = 'PEDIDOS_ADM_DELETAR_SUCESSO';
export const PEDIDOS_ADM_DELETAR_FALHA = 'PEDIDOS_ADM_DELETAR_FALHA';
export const PEDIDOS_ADM_DELETAR_RESET = 'PEDIDOS_ADM_DELETAR_RESET';

//rever isso
export const PEDIDO_ENVIAR_REQUEST = 'PEDIDO_ENVIAR_REQUEST';
export const PEDIDO_ENVIAR_SUCESSO = 'PEDIDO_ENVIAR_SUCESSO';
export const PEDIDO_ENVIAR_FALHA = 'PEDIDO_ENVIAR_FALHA';
export const PEDIDO_ENVIAR_RESET = 'PEDIDO_ENVIAR_RESET';

