export const PRODUTO_LISTA_REQUEST = 'PRODUTO_LISTA_REQUEST';
export const PRODUTO_LISTA_SUCESSO = 'PRODUTO_LISTA_SUCESSO';
export const PRODUTO_LISTA_FALHA = 'PRODUTO_LISTA_FALHA';

export const PRODUTO_DETALHES_REQUEST = 'PRODUTO_DETALHES_REQUEST';
export const PRODUTO_DETALHES_SUCESSO = 'PRODUTO_DETALHES_SUCESSO';
export const PRODUTO_DETALHES_FALHA = 'PRODUTO_DETALHES_FALHA';

export const PRODUTO_CRIAR_REQUEST = 'PRODUTO_CRIAR_REQUEST';
export const PRODUTO_CRIAR_SUCESSO = 'PRODUTO_CRIAR_SUCESSO';
export const PRODUTO_CRIAR_FALHA = 'PRODUTO_CRIAR_FALHA';
export const PRODUTO_CRIAR_RESET = 'PRODUTO_CRIAR_RESET';

export const PRODUTO_ATUALIZAR_REQUEST = 'PRODUTO_ATUALIZAR_REQUEST';
export const PRODUTO_ATUALIZAR_SUCESSO = 'PRODUTO_ATUALIZAR_SUCESSO';
export const PRODUTO_ATUALIZAR_FALHA = 'PRODUTO_ATUALIZAR_FALHA';
export const PRODUTO_ATUALIZAR_RESET = 'PRODUTO_ATUALIZAR_RESET';

export const PRODUTO_DELETAR_REQUEST = 'PRODUTO_DELETAR_REQUEST';
export const PRODUTO_DELETAR_SUCESSO = 'PRODUTO_DELETAR_SUCESSO';
export const PRODUTO_DELETAR_FALHA = 'PRODUTO_DELETAR_FALHA';
export const PRODUTO_DELETAR_RESET = 'PRODUTO_DELETAR_RESET';