export const USUARIO_LOGIN_REQUEST = 'USUARIO_LOGIN_REQUEST';
export const USUARIO_LOGIN_SUCESSO = 'USUARIO_LOGIN_SUCESSO';
export const USUARIO_LOGIN_FALHA = 'USUARIO_LOGIN_FALHA';

export const USUARIO_LOGOUT = 'USUARIO_LOGOUT';

export const USUARIO_REGISTRO_REQUEST = 'USUARIO_REGISTRO_REQUEST';
export const USUARIO_REGISTRO_SUCESSO = 'USUARIO_REGISTRO_SUCESSO';
export const USUARIO_REGISTRO_FALHA = 'USUARIO_REGISTRO_FALHA';

export const USUARIO_DETALHES_REQUEST = 'USUARIO_DETALHES_REQUEST';
export const USUARIO_DETALHES_SUCESSO = 'USUARIO_DETALHES_SUCESSO';
export const USUARIO_DETALHES_FALHA = 'USUARIO_DETALHES_FALHA';
export const USUARIO_DETALHES_RESET = 'USUARIO_DETALHES_RESET';

export const USUARIO_ATUALIZAR_REQUEST = 'USUARIO_ATUALIZAR_REQUEST';
export const USUARIO_ATUALIZAR_SUCESSO = 'USUARIO_ATUALIZAR_SUCESSO';
export const USUARIO_ATUALIZAR_FALHA = 'USUARIO_ATUALIZAR_FALHA';
export const USUARIO_ATUALIZAR_RESET = 'USUARIO_ATUALIZAR_RESET';

export const USUARIO_LISTA_REQUEST = 'USUARIO_LISTA_REQUEST';
export const USUARIO_LISTA_SUCESSO = 'USUARIO_LISTA_SUCESSO';
export const USUARIO_LISTA_FALHA = 'USUARIO_LISTA_FALHA';

export const DELETAR_USUARIO_REQUEST = 'DELETAR_USUARIO_REQUEST';
export const DELETAR_USUARIO_SUCESSO = 'DELETAR_USUARIO_SUCESSO';
export const DELETAR_USUARIO_FALHA = 'DELETAR_USUARIO_FALHA';
export const DELETAR_USUARIO_RESET = 'DELETAR_USUARIO_RESET';

export const USUARIO_ATUALIZAR_ADM_REQUEST = 'USUARIO_ATUALIZAR_ADM_REQUEST';
export const USUARIO_ATUALIZAR_ADM_SUCESSO = 'USUARIO_ATUALIZAR_ADM_SUCESSO';
export const USUARIO_ATUALIZAR_ADM_FALHA = 'USUARIO_ATUALIZAR_ADM_FALHA';
export const USUARIO_ATUALIZAR_ADM_RESET = 'USUARIO_ATUALIZAR_ADM_RESET';
